language: node_js
node_js:
  - node
  - lts/*
cache:
  directories:
    - ~/.npm
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version version-number
  - export PATH="$HOME/.yarn/bin:$PATH"
before_script:
  - npm install -g npm@latest
script:
  - npm ci
  - npx jest --ci
notifications:
  email: false
